### ISSUE TITLE
[Modrinth] Remove invalid project dependency

### ISSUE THREAD

**Issue by KruASe76** [Scubakay/litematica-enderchest-materials#9]
on Modrinth all versions from 0.0.3 refer to a project as a dependency that is invalid. this breaks mod installation feature in launchers such as PrismLauncher as it tries to install all the dependencies and in this case runs into an error.

removal of the invalid dependency should fix such issues.  
thanks :)

**Comment by Scubakay** [comment]
That's weird. I've been able to use the installation feature in Prism just fine. Which project does it refer to that breaks it?

**Comment by Scubakay** [comment]
That would be Litematica. The dependency can not be resolved by Modrinth because Litematica is not on Modrinth yet. Prism/Minecraft should be able to resolve it just fine. 

Have you added Litematica to the mods too?

Also, if there's any errors, could you copy and paste them here?

**Comment by KruASe76** [comment]
[here is the log part](https://gist.github.com/KruASe76/3bb8f276dfb84234abbd31b7507494c6)

and here is how it looks like
[prismlauncher_mod_download_error.webm](https://github.com/Scubakay/litematica-enderchest-materials/assets/55000336/47221ca7-4021-4de4-9454-a4d581569100)

**Comment by Scubakay** [comment]
Could you see if it helps if you download Litematica and Malilib first?
Malilib can now be found on Modrinth. Litematica is still on CurseForge.

**Comment by Scubakay** [comment]
I think this might be a bug on Prism's side, where they handle dependencies incorrectly, but I'm not sure.

**Comment by KruASe76** [comment]
> Could you see if it helps if you download Litematica and Malilib first?
Still the same, no matter from where Malilib was downloaded

> What version of Prism are you on? (I'm on 7.2)
8.3, on Fedora Linux if that matters

> a bug on Prism's side, where they handle dependencies incorrectly
well... if an project has an inexistent project listed as a required dependency, any mod downloader with dependency checks is totally expected to fail to resolve this imo

**Comment by Scubakay** [comment]
The mod does exist though. Only not on the same platform. I can't remove the dependency, because Minecraft itself needs to know about it. This mod adds a small little feature to Litematica so it needs the dependency.

But I might be wrong so I'm asking around on the Prism discord right now.

**Comment by KruASe76** [comment]
so the dependencies on Modrinth are automatically generated? well in that case it is really not your issue

i develop plugins and i have to manually add dependencies to projects on Modrinth

**Comment by Trial97** [comment]
This also fails on modrinth app:
![image](https://github.com/Scubakay/litematica-enderchest-materials/assets/42720688/f9f1576e-cfd3-4346-8119-173ecf132be0)

**Comment by Scubakay** [comment]
I think the dependencies are configured by mc-publish, which I use to publish to Modrinth.

**Comment by Scubakay** [comment]
@KruASe76 I removed the dependency from Modrinth. It should work now!
